[project]
name = "cult-booking-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "playwright>=1.56.0",
    "pytest>=9.0.1",
    "fastapi>=0.115.0",
    "uvicorn>=0.30.0",
]
